apiVersion: unfurl/v1alpha1
kind: Ensemble
spec:
  service_template:
    imports:
    - repository: unfurl
      file: configurators/docker-template.yaml
    topology_template:
      inputs:
        host:
          type: string
          default: 127.0.0.1
        hostport:
          type: integer
          default: 4000
        container_name:
          type: string
          default: jekyll
      outputs:
        site_url:
          value: 'http://{{"::jekyll::host" | eval }}:{{"::jekyll::hostport" | eval }}/'

      node_templates:
        jekyll:
          type: unfurl.nodes.Container.Application.Docker
          properties:
            name:  {get_input: container_name}
            hostport: {get_input: hostport}
            host: {get_input: host}
          artifacts:
            image:
              type: tosca.artifacts.Deployment.Image.Container.Docker
              # official jekyllrb image: https://github.com/envygeeks/jekyll-docker/blob/master/README.md
              file: jekyll/jekyll
          interfaces:
            defaults:
              inputs:
                configuration:
                  command: jekyll serve -P 4000 -t --incremental
                  published_ports:
                    - "{{ SELF.host }}:{{ SELF.hostport }}:4000" # host:container
                  volumes:
                    # unfurl project is a child of the main repo
                    - '{{ ".." | abspath("spec") }}:/srv/jekyll'
                    # map cache folder so we don't need to download gems every time:
                    - '{{ "vendor/bundle" | abspath("spec.local") }}:/usr/local/bundle'
